#include <stdio.h>

#define TEX_WIDTH 24
#define TEX_HEIGHT 16

#define RGB(val) ((val >> 16) & 0xFF), ((val >> 8) & 0xFF), (val & 0xFF)

#define BASEC RGB(0x3F3F74)
#define REDCC RGB(0xD95763)
#define WHITE RGB(0xFFFFFF)
#define TRANS RGB(0xFF00FF)

unsigned char array[TEX_WIDTH * TEX_HEIGHT * 3] = {
	TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, 
	TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS,
	TRANS, TRANS, TRANS, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, TRANS, TRANS, TRANS,
	TRANS, TRANS, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, TRANS, TRANS,
	TRANS, TRANS, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, TRANS, TRANS,
	TRANS, TRANS, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, TRANS, TRANS,
	TRANS, BASEC, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, BASEC, TRANS,
	BASEC, WHITE, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, WHITE, BASEC,
	BASEC, WHITE, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, WHITE, BASEC,
	TRANS, BASEC, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, BASEC, TRANS,
	TRANS, TRANS, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, TRANS, TRANS,
	TRANS, TRANS, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, TRANS, TRANS,
	TRANS, TRANS, BASEC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, REDCC, BASEC, TRANS, TRANS,
	TRANS, TRANS, TRANS, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, BASEC, TRANS, TRANS, TRANS,
	TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS,
	TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS, TRANS,
};

int main(void) {
	FILE * fp = fopen("out.raw", "w");

	if (fwrite(array, 1, TEX_WIDTH * TEX_HEIGHT * 3, fp) == 0) {
		printf("error writing\n");
		return -1;
	}

	fclose(fp);
}
